title: Tune a PIR
hero_image: images/banner.png
description: How to tune a PIR
original_url: 
theme: turquoise
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum:
interests: 
technologies: "electronics"
site_areas:
steps:
  - title: Tune a PIR
